name: coda11_3
channels:
  - pytorch
  - defaults
  - robostack-staging
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=1.0=mkl
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=23.7.4=py38h578d9bd_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - cryptography=41.0.3=py38hcdda232_0
  - cudatoolkit=11.3.1=h9edb442_10
  - ffmpeg=4.3=hf484d3e_0
  - fmt=10.1.1=h00ab1b0_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - jsonpatch=1.32=pyhd8ed1ab_0
  - jsonpointer=2.4=py38h578d9bd_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libarchive=3.6.2=h039dbb9_1
  - libcurl=8.3.0=hca28451_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_0
  - libiconv=1.17=h166bdaf_0
  - libmamba=1.5.1=h744094f_0
  - libmambapy=1.5.1=py38h5cd715c_0
  - libnghttp2=1.52.0=h61bc06f_0
  - libpng=1.6.37=h21135ba_2
  - libsolv=0.7.24=hfc55251_4
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_0
  - libtiff=4.3.0=hf544144_1
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mamba=1.5.1=py38haad2881_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.1.2=hd590300_0
  - pip=23.2.1=py38h06a4308_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.4=py38h0a891b7_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h0b41bf4_0
  - reproc-cpp=14.2.4=hcb278e6_0
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.32=py38h01eb140_0
  - ruamel.yaml.clib=0.2.7=py38h1de0b5d_1
  - setuptools=68.0.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.0=py38_cu113
  - typing_extensions=4.7.1=pyha770c72_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml-cpp=0.7.0=h27087fc_2
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - addict==2.4.0
      - ansi2html==1.8.0
      - appdirs==1.4.4
      - asttokens==2.4.0
      - attrs==23.1.0
      - backcall==0.2.0
      - ccimport==0.4.2
      - certifi==2023.7.22
      - click==8.1.7
      - comm==0.1.4
      - configargparse==1.7
      - contourpy==1.1.0
      - cumm-cu113==0.4.11
      - cycler==0.11.0
      - dash==2.13.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - easydict==1.10
      - executing==1.2.0
      - fastjsonschema==2.18.0
      - fire==0.5.0
      - flask==2.2.5
      - fonttools==4.42.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - imageio==2.31.3
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - ipython==8.12.2
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lark==1.1.7
      - llvmlite==0.41.0rc1
      - matplotlib==3.7.3
      - matplotlib-inline==0.1.6
      - nbformat==5.7.0
      - nest-asyncio==1.5.7
      - networkx==3.1
      - ninja==1.11.1
      - numba==0.58.0rc2
      - numpy==1.24.4
      - open3d==0.17.0
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathtools==0.1.2
      - pccm==0.4.8
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==3.10.0
      - portalocker==2.7.0
      - prompt-toolkit==3.0.39
      - protobuf==4.24.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybind11==2.11.1
      - pygments==2.16.1
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - retrying==1.3.4
      - rpds-py==0.10.3
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - sharedarray==3.2.3
      - smmap==5.0.0
      - spconv-cu113==2.3.6
      - stack-data==0.6.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.2.0
      - tifffile==2023.8.30
      - tqdm==4.66.1
      - traitlets==5.9.0
      - tzdata==2023.3
      - wandb==0.15.10
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.9
      - zipp==3.16.2
prefix: ~/miniconda3/envs/coda11_3
